server:
  port: 8520
  tomcat:
    uri-encoding: UTF-8
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    max-threads: 1000
    min-spare-threads: 30
    connection-timeout: 5000ms
    servlet:
      context-path: /

spring:
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  mvc:
    view:
      suffix: .html
  application:
    name: happy-sky
  profiles:
    active: @package.environment@
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

    throw-exception-if-no-handler-found: true
  devtools:
    livereload:
      port: 8801
  info: #定义各种额外的详情给服务端显示
    app:
      name: "@project.name@" #从pom.xml中获取
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@project.parent.version@"
  main:
    allow-bean-definition-overriding: true

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.happy.sky.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#FTP上传文件配置
ftp:
  host: ftp.xf-admin.zhxf.ltd
  username: static_uploader
  password : 0pfTaaoU4wa0TJ5lGWG5
  port: 21
  rootDir: sky/

logging:
  config: classpath:logback.xml